# Generated by Django 5.1.3 on 2024-11-09 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restroom',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(help_text="Расположение туалета, например, 'Коридор 2 этажа'", max_length=100)),
                ('max_capacity', models.PositiveIntegerField(help_text='Максимальное количество людей')),
                ('current_occupancy', models.PositiveIntegerField(default=0, help_text='Текущее количество людей')),
            ],
        ),
    ]
